"use client";

import { ScrapyPage } from "@/components/ScrapyPage";
import { CodeBlock } from "@/components/CodeBlock";
import { Collapsible } from "@/components/Collapsible";
import { Callout } from "@/components/Callout";
import { Code } from "@/components/Code";

export default function DebuggingSpidersPage() {
  return (
    <ScrapyPage
      breadcrumb="Debugging"
      title="Debugging Spiders"
      subtitle="Scrapy provides several tools for debugging: the interactive shell, the parse command, logging, and standard Python breakpoints."
      prev={{ label: "FAQ", href: "/scrapy/solving-problems/faq" }}
      next={{ label: "Contracts", href: "/scrapy/solving-problems/contracts" }}
    >
      <div className="space-y-6">
        <Collapsible title="Scrapy Shell" defaultOpen>
          <p className="text-sm text-[#b0aea5] mb-3">
            Launch <Code>scrapy shell</Code> with a URL to interactively test
            selectors before writing spider code.
          </p>
          <CodeBlock language="bash" title="shell debugging">
{`scrapy shell "https://docs.example.com/api"
>>> response.css('h1::text').get()
'API Reference'
>>> response.css('div.method').getall()`}
          </CodeBlock>
        </Collapsible>

        <Collapsible title="The Parse Command">
          <p className="text-sm text-[#b0aea5] mb-3">
            Run a single URL through a specific callback without a full crawl
            using <Code>scrapy parse</Code>.
          </p>
          <CodeBlock language="bash" title="parse command">
{`scrapy parse --spider=docs \\
  --callback=parse_detail \\
  "https://docs.example.com/api/auth"
# Shows items and requests generated by parse_detail`}
          </CodeBlock>
        </Collapsible>

        <Collapsible title="Python Breakpoints">
          <p className="text-sm text-[#b0aea5] mb-3">
            Drop a <Code>breakpoint()</Code> in any callback to pause execution
            and inspect the response object in pdb.
          </p>
          <CodeBlock language="python" title="breakpoint debugging">
{`def parse(self, response):
    breakpoint()  # drops into pdb
    title = response.css("h1::text").get()
    yield {"title": title}`}
          </CodeBlock>
        </Collapsible>

        <Collapsible title="Verbose Logging">
          <p className="text-sm text-[#b0aea5] mb-3">
            Temporarily set <Code>LOG_LEVEL = "DEBUG"</Code> to see every request,
            response, and middleware action during a crawl.
          </p>
          <CodeBlock language="bash" title="debug run">
{`scrapy crawl docs -s LOG_LEVEL=DEBUG 2>&1 | head -100`}
          </CodeBlock>
        </Collapsible>

        <Callout type="tip">
          In AgentTasks, we use <Code>scrapy parse</Code> extensively to validate
          selectors before committing spider changes.
        </Callout>
      </div>
    </ScrapyPage>
  );
}
