// .jade/surfaces/registry.ts — Concrete page registry for all Anthropic doc surfaces
//
// Version-controlled. Every page the user listed is registered here.
// Edits bump the version via bumpVersion(). Data models flow downstream
// as structured inputs to agents, YAML schemas, and programmatic scripts.

import { toPageSlug, type PageSlug } from '../models/base.js';
import {
  type DocPage,
  type CapabilityPage,
  type ToolPage,
  type ToolReferencePage,
  type ToolInfrastructurePage,
  type ContextManagementPage,
  type FilesAssetsPage,
  type AgentSkillPage,
  createPageRegistry,
} from './doc-surface.js';

// ─── Helper ─────────────────────────────────────────────────────────────────

const slug = (s: string): PageSlug => toPageSlug(s);
const noChildren: readonly PageSlug[] = [];

// ─── Capabilities Surface ───────────────────────────────────────────────────

const capabilities: readonly CapabilityPage[] = [
  {
    slug: slug('extended-thinking'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking',
    title: 'Extended Thinking',
    surface: 'capabilities',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Extended Thinking',
    apiEndpoint: '/v1/messages',
    sdkMethod: 'messages.create({ thinking: { type: "enabled" } })',
    betaStatus: false,
    requiredModel: 'claude-opus-4-6',
  },
  {
    slug: slug('adaptive-thinking'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#adaptive-thinking',
    title: 'Adaptive Thinking',
    surface: 'capabilities',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: slug('extended-thinking'),
    childSlugs: noChildren,
    capabilityName: 'Adaptive Thinking',
    apiEndpoint: '/v1/messages',
    sdkMethod: 'messages.create({ thinking: { type: "enabled", budget_tokens: N } })',
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('effort'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#effort',
    title: 'Effort',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('extended-thinking'),
    childSlugs: noChildren,
    capabilityName: 'Effort Control',
    apiEndpoint: '/v1/messages',
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('fast-mode'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/fast-mode',
    title: 'Fast Mode',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Fast Mode',
    apiEndpoint: null,
    sdkMethod: null,
    betaStatus: true,
    requiredModel: null,
  },
  {
    slug: slug('structured-outputs'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/structured-outputs',
    title: 'Structured Outputs',
    surface: 'capabilities',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Structured Outputs',
    apiEndpoint: '/v1/messages',
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('citations'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/citations',
    title: 'Citations',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Citations',
    apiEndpoint: '/v1/messages',
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('streaming-messages'),
    url: 'https://docs.anthropic.com/en/api/streaming',
    title: 'Streaming Messages',
    surface: 'capabilities',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Streaming Messages',
    apiEndpoint: '/v1/messages',
    sdkMethod: 'messages.stream()',
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('batch-processing'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/message-batches',
    title: 'Batch Processing',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Batch Processing',
    apiEndpoint: '/v1/messages/batches',
    sdkMethod: 'batches.create()',
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('pdf-support'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/pdf-support',
    title: 'PDF Support',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'PDF Support',
    apiEndpoint: '/v1/messages',
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('search-results'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/search-results',
    title: 'Search Results',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Search Results',
    apiEndpoint: null,
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('multilingual-support'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/multilingual-support',
    title: 'Multilingual Support',
    surface: 'capabilities',
    priority: 'low',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Multilingual Support',
    apiEndpoint: null,
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('embeddings'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/embeddings',
    title: 'Embeddings',
    surface: 'capabilities',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Embeddings',
    apiEndpoint: null,
    sdkMethod: null,
    betaStatus: false,
    requiredModel: null,
  },
  {
    slug: slug('vision'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/vision',
    title: 'Vision',
    surface: 'capabilities',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: noChildren,
    capabilityName: 'Vision',
    apiEndpoint: '/v1/messages',
    sdkMethod: 'messages.create({ content: [{ type: "image" }] })',
    betaStatus: false,
    requiredModel: null,
  },
];

// ─── Tools Surface ──────────────────────────────────────────────────────────

const tools: readonly ToolPage[] = [
  {
    slug: slug('tools-overview'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview',
    title: 'Tools Overview',
    surface: 'tools',
    priority: 'critical',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [slug('how-tool-use-works'), slug('define-tools'), slug('handle-tool-calls')],
    toolSection: 'overview',
    hasCodeExamples: true,
    relatedTools: [],
  },
  {
    slug: slug('how-tool-use-works'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use',
    title: 'How Tool Use Works',
    surface: 'tools',
    priority: 'critical',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'how-it-works',
    hasCodeExamples: true,
    relatedTools: [],
  },
  {
    slug: slug('build-tool-using-agent'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/tutorial',
    title: 'Tutorial: Build a Tool-Using Agent',
    surface: 'tools',
    priority: 'critical',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'tutorial',
    hasCodeExamples: true,
    relatedTools: [],
  },
  {
    slug: slug('define-tools'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/define-tools',
    title: 'Define Tools',
    surface: 'tools',
    priority: 'critical',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'define-tools',
    hasCodeExamples: true,
    relatedTools: [slug('handle-tool-calls')],
  },
  {
    slug: slug('handle-tool-calls'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/handle-tool-calls',
    title: 'Handle Tool Calls',
    surface: 'tools',
    priority: 'critical',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'handle-tool-calls',
    hasCodeExamples: true,
    relatedTools: [slug('define-tools')],
  },
  {
    slug: slug('parallel-tool-use'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/parallel-tool-use',
    title: 'Parallel Tool Use',
    surface: 'tools',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'parallel-tool-use',
    hasCodeExamples: true,
    relatedTools: [slug('handle-tool-calls')],
  },
  {
    slug: slug('tool-runner-sdk'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/tool-runner',
    title: 'Tool Runner (SDK)',
    surface: 'tools',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'tool-runner-sdk',
    hasCodeExamples: true,
    relatedTools: [],
  },
  {
    slug: slug('strict-tool-use'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/strict-tool-use',
    title: 'Strict Tool Use',
    surface: 'tools',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'strict-tool-use',
    hasCodeExamples: true,
    relatedTools: [],
  },
  {
    slug: slug('tool-use-prompt-caching'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/tool-use-with-prompt-caching',
    title: 'Tool Use with Prompt Caching',
    surface: 'tools',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'prompt-caching',
    hasCodeExamples: true,
    relatedTools: [slug('prompt-caching')],
  },
  {
    slug: slug('server-tools'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/server-tools',
    title: 'Server Tools',
    surface: 'tools',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'server-tools',
    hasCodeExamples: true,
    relatedTools: [slug('web-search-tool'), slug('web-fetch-tool')],
  },
  {
    slug: slug('tools-troubleshooting'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/troubleshooting',
    title: 'Troubleshooting',
    surface: 'tools',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('tools-overview'),
    childSlugs: [],
    toolSection: 'troubleshooting',
    hasCodeExamples: false,
    relatedTools: [],
  },
];

// ─── Tool Reference Surface ─────────────────────────────────────────────────

const toolReference: readonly ToolReferencePage[] = [
  {
    slug: slug('web-search-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/web-search-tool',
    title: 'Web Search Tool',
    surface: 'tool-reference',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'web_search',
    toolType: 'web-search',
    inputSchema: '{ type: "web_search_20250305" }',
    serverSide: true,
  },
  {
    slug: slug('web-fetch-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/web-fetch-tool',
    title: 'Web Fetch Tool',
    surface: 'tool-reference',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'web_fetch',
    toolType: 'web-fetch',
    inputSchema: '{ url: string, format?: "text"|"markdown" }',
    serverSide: true,
  },
  {
    slug: slug('code-execution-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/code-execution-tool',
    title: 'Code Execution Tool',
    surface: 'tool-reference',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'code_execution',
    toolType: 'code-execution',
    inputSchema: '{ type: "code_execution_20250522" }',
    serverSide: true,
  },
  {
    slug: slug('memory-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/memory-tool',
    title: 'Memory Tool',
    surface: 'tool-reference',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'memory',
    toolType: 'memory',
    inputSchema: null,
    serverSide: true,
  },
  {
    slug: slug('bash-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/bash-tool',
    title: 'Bash Tool',
    surface: 'tool-reference',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'bash',
    toolType: 'bash',
    inputSchema: '{ command: string, restart?: boolean }',
    serverSide: false,
  },
  {
    slug: slug('computer-use-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/computer-use-tool',
    title: 'Computer Use Tool',
    surface: 'tool-reference',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'computer',
    toolType: 'computer-use',
    inputSchema: '{ action: string, coordinate?: [x,y] }',
    serverSide: false,
  },
  {
    slug: slug('text-editor-tool'),
    url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/text-editor-tool',
    title: 'Text Editor Tool',
    surface: 'tool-reference',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [],
    toolName: 'text_editor',
    toolType: 'text-editor',
    inputSchema: '{ command: "view"|"create"|"str_replace"|"insert", path: string }',
    serverSide: false,
  },
];

// ─── Tool Infrastructure Surface ────────────────────────────────────────────

const toolInfra: readonly ToolInfrastructurePage[] = [
  {
    slug: slug('manage-tool-context'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/manage-tool-context',
    title: 'Manage Tool Context',
    surface: 'tool-infrastructure',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: [],
    infraTopic: 'manage-context',
  },
  {
    slug: slug('tool-combinations'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/tool-combinations',
    title: 'Tool Combinations',
    surface: 'tool-infrastructure',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [],
    infraTopic: 'tool-combinations',
  },
  {
    slug: slug('tool-search'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/tool-search',
    title: 'Tool Search',
    surface: 'tool-infrastructure',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: null,
    childSlugs: [],
    infraTopic: 'tool-search',
  },
  {
    slug: slug('programmatic-tool-calling'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/programmatic-tool-calling',
    title: 'Programmatic Tool Calling',
    surface: 'tool-infrastructure',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    infraTopic: 'programmatic-calling',
  },
  {
    slug: slug('fine-grained-tool-streaming'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/fine-grained-streaming',
    title: 'Fine-Grained Tool Streaming',
    surface: 'tool-infrastructure',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    infraTopic: 'fine-grained-streaming',
  },
];

// ─── Context Management Surface ─────────────────────────────────────────────

const contextMgmt: readonly ContextManagementPage[] = [
  {
    slug: slug('context-windows'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/context-windows',
    title: 'Context Windows',
    surface: 'context-management',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [slug('compaction'), slug('context-editing')],
    contextTopic: 'context-windows',
    affectsTokenCount: true,
  },
  {
    slug: slug('compaction'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/compaction',
    title: 'Compaction',
    surface: 'context-management',
    priority: 'high',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('context-windows'),
    childSlugs: [],
    contextTopic: 'compaction',
    affectsTokenCount: true,
  },
  {
    slug: slug('context-editing'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/context-editing',
    title: 'Context Editing',
    surface: 'context-management',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('context-windows'),
    childSlugs: [],
    contextTopic: 'context-editing',
    affectsTokenCount: true,
  },
  {
    slug: slug('prompt-caching'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching',
    title: 'Prompt Caching',
    surface: 'context-management',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    contextTopic: 'prompt-caching',
    affectsTokenCount: true,
  },
  {
    slug: slug('token-counting'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/token-counting',
    title: 'Token Counting',
    surface: 'context-management',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    contextTopic: 'token-counting',
    affectsTokenCount: true,
  },
];

// ─── Files & Assets Surface ─────────────────────────────────────────────────

const filesAssets: readonly FilesAssetsPage[] = [
  {
    slug: slug('files-api'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/files',
    title: 'Files API',
    surface: 'files-assets',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: null,
    childSlugs: [],
    fileType: 'multi',
    maxSizeMb: 500,
  },
];

// ─── Agent Skills Surface ───────────────────────────────────────────────────

const agentSkills: readonly AgentSkillPage[] = [
  {
    slug: slug('agent-skills-overview'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/overview',
    title: 'Agent Skills Overview',
    surface: 'agent-skills',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml'],
    parentSlug: null,
    childSlugs: [slug('agent-skills-quickstart'), slug('agent-skills-best-practices')],
    skillTopic: 'overview',
    requiresEnterprise: false,
  },
  {
    slug: slug('agent-skills-quickstart'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/quickstart',
    title: 'Agent Skills Quickstart',
    surface: 'agent-skills',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('agent-skills-overview'),
    childSlugs: [],
    skillTopic: 'quickstart',
    requiresEnterprise: false,
  },
  {
    slug: slug('agent-skills-best-practices'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/best-practices',
    title: 'Agent Skills Best Practices',
    surface: 'agent-skills',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown'],
    parentSlug: slug('agent-skills-overview'),
    childSlugs: [],
    skillTopic: 'best-practices',
    requiresEnterprise: false,
  },
  {
    slug: slug('skills-enterprise'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/enterprise',
    title: 'Skills for Enterprise',
    surface: 'agent-skills',
    priority: 'medium',
    agentStrategy: 'direct-fetch-extract',
    outputFormats: ['markdown'],
    parentSlug: slug('agent-skills-overview'),
    childSlugs: [],
    skillTopic: 'enterprise',
    requiresEnterprise: true,
  },
  {
    slug: slug('claude-api-skill'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/claude-api-skill',
    title: 'Claude API Skill',
    surface: 'agent-skills',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'yaml', 'typescript'],
    parentSlug: slug('agent-skills-overview'),
    childSlugs: [],
    skillTopic: 'claude-api-skill',
    requiresEnterprise: false,
  },
  {
    slug: slug('skills-with-api'),
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/agent-skills/using-skills-with-api',
    title: 'Using Skills with the API',
    surface: 'agent-skills',
    priority: 'high',
    agentStrategy: 'headless-subagent',
    outputFormats: ['markdown', 'typescript'],
    parentSlug: slug('agent-skills-overview'),
    childSlugs: [],
    skillTopic: 'skills-with-api',
    requiresEnterprise: false,
  },
];

// ─── Full Registry ──────────────────────────────────────────────────────────

export const ALL_DOC_PAGES: readonly DocPage[] = [
  ...capabilities,
  ...tools,
  ...toolReference,
  ...toolInfra,
  ...contextMgmt,
  ...filesAssets,
  ...agentSkills,
];

export const DOC_PAGE_REGISTRY = createPageRegistry(ALL_DOC_PAGES);
